# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: ebs
# spec:
#   accessModes:
#   - ReadWriteOnce
#   capacity:
#     storage: 40Gi
#   csi:
#     driver: ebs.csi.aws.com
#     fsType: ext4
#     volumeHandle: vol-0e1eb0752f18137e6 ###i have to create the volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 40Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0e1eb0752f18137e6