apiVersion: v1
kind: Pod
metadata:
  name: nginx
  Namespace: expense
spec:
#one pod can contain multiple containers
#minimum one (or) mini container as to be run
  containers:
  - name: kuber
    image: nginx