kind: Pod
apiVersion: v1
metadata:
  name: multiserver
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"] ##this is run for some time