kind: pod
apiVersion: v1
metadata:
  name: multiple-containers
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#   - name: almalinux
#     image: almalinux:9
#     command: ["sleep", "1000"]
  spec:
    containers:
    - name: nginx
      image: nginx
    - name: almalinux
      image: almalinux:9
      command: ["sleep","1000"]