apiVersion: v1
kind: Pod
metadata:
  name: env
spec: 
  containers:
  - name: nginx
    image: nginx
    resource:
      requests:
        memory: "68Mi"
        cpu: "100m"
      limits: 
        memory: "128Mi"
        cpu: "150m" 