kind: Service
apiVersion: v1
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector: # labels will used here for selecting the pod
    project: expense
    environment: dev
    component: backend 
    demo: np
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodeport: 30007
---
kind: Pod
apiVersion: v1
metadata:
  name: backend-np
  labels:
    project: expense
    environment: dev
    component: backend
    demo: np
spec:
  containers:
  - name: nginx
    image: nginx